services:
  app:
    image: node:20.9
    working_dir: /app
    user: node
    ports:
      - 8080:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    entrypoint: npm
    command:
      - run
      - dev
    restart: always
  deps:
    image: node:20.9
    working_dir: /app
    user: node
    volumes:
      - .:/app
    entrypoint: npm
    command: i
    profiles:
      - cli
  db:
    image: postgres:16.2-bookworm
    volumes:
      - db:/var/lib/postgresql/data
      - ./dump.sql:/var/tmp/dump.sql
    ports:
      - 5432:5432
    env_file:
      - db.env
    healthcheck:
      test: ["CMD-SHELL", "psql -h 127.0.0.1 -U $${POSTGRES_USER} -c select 1 -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

volumes:
  db: